Script started on Fri 06 Nov 2015 09:38:37 PM PST
[jreim001@hammer rshell]$ bin/rshell
[jreim001@hammer.cs.ucr.edu] $ echo hello; date; pwd; ls -l; echo goodbye
hello
Fri Nov	 6 21:39:07 PST 2015
/home/csmajs/jreim001/CS100/rshell
total 44
drwxr-xr-x 2 jreim001 csmajs  4096 Nov	6 21:26 bin
-rw-r--r-- 1 jreim001 csmajs 18651 Nov	5 11:19 LICENSE.txt
-rw-r--r-- 1 jreim001 csmajs   285 Nov	6 20:19 Makefile
-rw-r--r-- 1 jreim001 csmajs	 0 Nov	6 21:38 multi.script
-rw-r--r-- 1 jreim001 csmajs   840 Nov	5 11:19 README.md
drwxr-xr-x 2 jreim001 csmajs  4096 Nov	6 21:25 src
drwxr-xr-x 2 jreim001 csmajs  4096 Nov	6 21:34 tests
-rw-r--r-- 1 jreim001 csmajs   179 Nov	6 21:27 typescript
goodbye
[jreim001@hammer.cs.ucr.edu] $ ehco hello && echo oops, that was a typo || date && pwd
execve failed: No such file or directory
Fri Nov	 6 21:39:55 PST 2015
/home/csmajs/jreim001/CS100/rshell
[jreim001@hammer.cs.ucr.edu] $ date; pwd && echo here's a proper one || mkdir test
Fri Nov	 6 21:40:48 PST 2015
/home/csmajs/jreim001/CS100/rshell
here's a proper one
[jreim001@hammer.cs.ucr.edu] $ exit
[jreim001@hammer rshell]$ exit
exit

Script done on Fri 06 Nov 2015 09:41:04 PM PST
